# Generated by Django 3.1.2 on 2020-10-17 15:52

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0054_auto_20201017_1752'),
        ('accounts', '0002_remove_profile_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
