# Generated by Django 3.1.1 on 2020-09-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.CharField(choices=[('1', 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1, max_length=1),
        ),
    ]
