# Generated by Django 3.1.1 on 2020-09-29 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200925_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_departure', models.DateTimeField()),
                ('date_of_arrival', models.DateTimeField()),
                ('date_of_return', models.DateTimeField()),
                ('days', models.DurationField()),
                ('catering_option', models.CharField(choices=[('BB', 'bed & breakfast'), ('HB', 'half board'), ('FB', 'full board'), ('Al', 'all inclusive'), ('OV', 'overnight'), ('SC', 'self catering'), ('PP', 'program package'), ('ZPR', 'ZPR')], max_length=20)),
                ('price_for_adult', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_for_child', models.DecimalField(decimal_places=2, max_digits=6)),
                ('promoting', models.BooleanField(default=False)),
                ('adults_number', models.IntegerField(default=0)),
                ('kids_number', models.IntegerField(default=0)),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_airport_trips', to='core.airport')),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_city_trips', to='core.city')),
                ('arrival_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_hotel_trips', to='core.hotel')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_airport_trips', to='core.airport')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_city_trips', to='core.city')),
            ],
        ),
        migrations.CreateModel(
            name='TripPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants_data', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_purchases', to='core.trip')),
            ],
        ),
    ]
