# Generated by Django 3.1.1 on 2020-09-29 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_trip_trippurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='days',
        ),
    ]
