# Generated by Django 3.1.1 on 2020-09-29 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_trip_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=2), verbose_name=datetime.timedelta(0)),
        ),
    ]
