# Generated by Django 3.1.1 on 2020-09-29 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200929_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
