# Generated by Django 3.1.1 on 2020-09-29 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200929_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=-10)),
        ),
    ]
