# Generated by Django 3.1.1 on 2020-09-29 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200929_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='date_of_arrival',
            new_name='arrival_date',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='date_of_departure',
            new_name='departure_date',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='date_of_return',
            new_name='return_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='duration',
        ),
    ]
