# Generated by Django 3.1.1 on 2020-09-29 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200929_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='promoting',
            new_name='promoted',
        ),
    ]
