# Generated by Django 3.1.1 on 2020-09-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200929_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.CharField(choices=[('*', 1), ('**', 2), ('***', 3), ('****', 4), ('*****', 5)], default=1, max_length=5),
        ),
    ]
