# Generated by Django 3.1.2 on 2020-10-04 09:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200930_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_image',
            field=models.FileField(null=True, upload_to=core.models.get_city_image_path),
        ),
        migrations.AddField(
            model_name='hotel',
            name='air_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='swimming_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=5),
        ),
    ]
