# Generated by Django 3.1.2 on 2020-10-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201004_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='restaurant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='room_service',
            field=models.BooleanField(default=False),
        ),
    ]
