# Generated by Django 3.1.2 on 2020-10-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20201004_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.CharField(default='', max_length=500),
        ),
    ]
