# Generated by Django 3.1.2 on 2020-10-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_hotel_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', 3), ('4', 4), ('5', '5')], default=1, max_length=5),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='swimming_pool',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
