# Generated by Django 3.1.2 on 2020-10-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201004_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='swimming_pool',
            field=models.BooleanField(choices=[(True, 'Yes'), ('No', False)], default=False),
        ),
    ]
