# Generated by Django 3.1.2 on 2020-10-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20201004_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='swimming_pool',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='wifi',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
