# Generated by Django 3.1.2 on 2020-10-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20201004_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='swimming_pool',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='wifi',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
