# Generated by Django 3.1.2 on 2020-10-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20201004_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='swimming_pool',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='wifi',
            field=models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], default=False),
        ),
    ]
