# Generated by Django 3.1.2 on 2020-10-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20201004_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='air_condition',
            field=models.CharField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='gym',
            field=models.CharField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='restaurant',
            field=models.CharField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='room_service',
            field=models.CharField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], default='No', max_length=10),
        ),
    ]
