# Generated by Django 3.1.2 on 2020-10-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20201004_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
