# Generated by Django 3.1.2 on 2020-10-04 12:57

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20201004_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_image',
            field=models.FileField(null=True, upload_to=core.models.get_hotel_image_path),
        ),
    ]
