# Generated by Django 3.1.2 on 2020-10-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_hotel_hotel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
        migrations.AlterField(
            model_name='trip',
            name='catering_option',
            field=models.CharField(choices=[('bed & breakfast', 'BB'), ('HB', 'half board'), ('FB', 'full board'), ('Al', 'all inclusive'), ('OV', 'overnight'), ('SC', 'self catering'), ('PP', 'program package'), ('ZPR', 'ZPR')], max_length=20),
        ),
    ]
