# Generated by Django 3.1.2 on 2020-10-10 14:10

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20201006_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_image',
            field=models.FileField(null=True, upload_to=core.models.get_country_image_path),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_image2',
            field=models.FileField(null=True, upload_to=core.models.get_hotel_image_path),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='catering_option',
            field=models.CharField(choices=[('Bed & Breakfast', 'BB'), ('Half board', 'HB'), ('Full board', 'FB'), ('All inclusive', 'Al'), ('Overnight', 'OV'), ('Self catering', 'SC'), ('Program package', 'PP'), ('ZPR', 'ZPR')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price_for_adult',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price_for_child',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
