# Generated by Django 3.1.2 on 2020-10-14 08:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_comment'),
        ('core', '0039_auto_20201010_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 10, 14, 8, 0, 24, 115167, tzinfo=utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.profile')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.trip')),
            ],
        ),
    ]
