# Generated by Django 3.1.2 on 2020-10-14 09:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20201014_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 9, 33, 3, 569938, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='trip',
        ),
        migrations.AddField(
            model_name='comment',
            name='trip',
            field=models.ManyToManyField(to='core.Trip'),
        ),
    ]
