# Generated by Django 3.1.2 on 2020-10-14 09:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20201014_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 9, 40, 34, 606708, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='trip',
        ),
        migrations.AddField(
            model_name='comment',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.trip'),
        ),
    ]
