# Generated by Django 3.1.2 on 2020-10-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20201015_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='back_home_date',
            field=models.DateTimeField(null=True),
        ),
    ]
