# Generated by Django 3.1.2 on 2020-10-16 13:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_trip_back_home_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_image2',
            field=models.ImageField(null=True, upload_to=core.models.get_country_image_path),
        ),
    ]
