# Generated by Django 3.1.2 on 2020-10-18 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20201017_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trippurchase',
            name='adults_number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='trippurchase',
            name='kids_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='trippurchase',
            name='test_char_field',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
